TickerData
const int TickerData::NA_VAL
Fill constant for unavailable data.
TickerData.cpp Implementation of TickerData.h Created by Salil Maharjan on 4/30/20. Copyright © 2020 Salil Maharjan. All rights reserved.
Referenced by Simulator::RunSimulation, calculateMACDfields.
std::string TickerData::m_tickerName
Stock ticker name.
Referenced by SetTradingDateRange, GetMACDSignal, parseTickerData, PrintAllColumns.
std::vector<double> TickerData::m_tickerData[TICKER_FIELDS::END_TICKER_FIELDS][TICKER_FIELDS::END_TICKER_FIELDS]
TickerData data for a stock in memory.
Referenced by GetMACDSignal, parseTickerData, calculateMACDfields, PrintDataHead, PrintAllColumns, GetCurrentDataOf, GetCloseYesterday.
std::vector<DateTime*> TickerData::m_tickerDates
TickerData dates of the price data.
Referenced by SetTradingDateRange, parseTickerData, PrintDataHead, PrintAllColumns.
int TickerData::m_tradingDateIndexStart
Trading start date index in m_tickerDates.
Referenced by SetTradingDateRange, GetMACDSignal, GetCurrentDataOf, GetCloseYesterday.
int TickerData::m_tradingDateIndexEnd
Trading end date index in m_tickerDates.
Referenced by SetTradingDateRange, GetMACDSignal.
TickerData::TickerData(std::string &a_tickerName, const std::string &a_directory)
Parameterized constructor to create a ticker object.
TickerData::TickerData. Parameterized constructor to create a ticker object a_tickerName string Name of ticker a_directory string Price data directory path. Salil Maharjan 4/30/20.
References calculateMACDfields, parseTickerData.
double TickerData::GetCurrentDataOf(TICKER_FIELDS a_field)
Get today's data of a_field.
References m_tickerData, m_tradingDateIndexStart.
Referenced by Simulator::RunSimulation.
double TickerData::GetCloseYesterday()
Get yesterday's close price.
References CLOSE, m_tickerData, m_tradingDateIndexStart.
void TickerData::SetTradingDateRange(DateTime *a_startDate, DateTime *a_endDate)
Method to set trading date range.
TickerData::SetTradingDateRange. Method to set trading date range. a_startDate DateTime* Start date of simulation to set. a_endDate DateTime* End date of simulation to set. Salil Maharjan 4/30/20.
References DateTime::GetASCIIDate, i, m_tickerDates, m_tickerName, m_tradingDateIndexEnd, m_tradingDateIndexStart.
Referenced by Simulator::RunSimulation.
double TickerData::GetMACDSignal()
Get current date's MACD signal.
TickerData::GetMACDSignal. Get current date's MACD signal. double The current MACD signal. Salil Maharjan 4/30/20.
References m_tickerData, m_tickerName, m_tradingDateIndexEnd, m_tradingDateIndexStart, MACD_HIST.
Referenced by Simulator::calculateSignal.
TickerData::~TickerData()=default
Default deconstructor.
void TickerData::PrintDataHead()
Print head of data columns.
TickerData::PrintDataHead Method to print first 10 data entries for the ticker object. Only print data fields. Used for debugging and checking. Salil Maharjan 4/30/20.
References ADJ_CLOSE, CLOSE, DIVIDEND, HIGH, i, LOW, m_tickerData, m_tickerDates, OPEN, SHARE_OUTSTANDING, SPLIT, VOLUME, VWAP.
void TickerData::PrintAllColumns()
Print sample of all columns including data and calculated columns.
TickerData::PrintAllColumns Method to print a sample of data for all data and calculated columns. Used for debugging and checking. Salil Maharjan 4/30/20.
References ADJ_CLOSE, CLOSE, DIVIDEND, FAST_EMA, HIGH, i, LOW, m_tickerData, m_tickerDates, m_tickerName, MACD_HIST, MACD_LINE, OPEN, SHARE_OUTSTANDING, SIG_LINE, SLOW_EMA, SPLIT, VOLUME, VWAP.
TickerData::TickerData()=default
Default constructor.
void TickerData::parseTickerData(const std::string &a_directory)
Parse ticker data from data source files.
TickerData::parseTickerData. Parse ticker data from data source files. a_directory string Path where the price data is located. Salil Maharjan 4/30/20.
References i, m_tickerData, m_tickerDates, m_tickerName, Utilities::trimBlanks.
Referenced by TickerData.
void TickerData::calculateMACDfields()
Calculate MACD fields and append to the ticker data.
TickerData::calculateMACDfields Calculate MACD fields and append to the ticker data. Salil Maharjan 4/30/20.
References CLOSE, FAST_EMA, i, m_tickerData, MACD_HIST, MACD_LINE, NA_VAL, SIG_LINE, SLOW_EMA.
Referenced by TickerData.