Simulator
const std::string Simulator::UNIVERSE_PATH_PARAM
[DIRECTORY DATA]
Referenced by checkParameters, loadParameters.
const std::string Simulator::TICKER_PATH_PARAM
Referenced by checkParameters, loadParameters.
const std::string Simulator::PORTFOLIO_CAPITAL
[PORTFOLIO DATA]
Referenced by checkParameters, loadParameters.
const std::string Simulator::MAX_CAPITAL_PER_STOCK_PARAM
Referenced by checkParameters, loadParameters.
const std::string Simulator::PERIOD_START_DATE
[SIMULATION PERIOD]
Referenced by checkParameters, loadParameters.
const std::string Simulator::PERIOD_END_DATE
Referenced by checkParameters, loadParameters.
const std::string Simulator::ENTRY_SIGNAL_PARAM
[SIGNAL THRESHOLDS]
Referenced by checkParameters, loadParameters.
const std::string Simulator::EXIT_SIGNAL_PARAM
Referenced by checkParameters, loadParameters.
const std::string Simulator::MAX_POS_PER_STOCK
[TRADING PARAMETERS]
Referenced by checkParameters, loadParameters.
const std::string Simulator::DAYS_IN_POS_PARAM
Referenced by checkParameters, loadParameters.
const std::string Simulator::STOP_LOSS_PARAM
Referenced by checkParameters, loadParameters.
const std::string Simulator::DAILY_PUB_PARAM
[PUBLICATION PARAMETERS]
Referenced by checkParameters, loadParameters.
const std::string Simulator::MONTHLY_PUB_PARAM
Referenced by checkParameters, loadParameters.
const std::string Simulator::TRANSACTION_PUB_PARAM
Referenced by checkParameters, loadParameters.
const std::string Simulator::SIGNAL_PUB_PARAM
Referenced by checkParameters, loadParameters.
std::string Simulator::m_universePath
Member variables from the configuration file [DIRECTORY DATA]
Referenced by initializeSimulator, loadParameters.
std::string Simulator::m_tickerPath
Referenced by initializeSimulator, loadParameters.
double Simulator::m_portfolioCapital
[PORTFOLIO DATA]
Referenced by loadParameters, initializeTradingTickers.
double Simulator::m_capitalLimitPerStock
Referenced by loadParameters, initializeTradingTickers.
double Simulator::m_entrySignal
[SIGNAL THRESHOLDS]
Referenced by loadParameters, makeTrade.
double Simulator::m_exitSignal
Referenced by loadParameters, makeTrade.
DateTime* Simulator::m_startDate
[SIMULATION PERIOD]
Referenced by RunSimulation, loadParameters, verifyDateParameters.
DateTime* Simulator::m_endDate
Referenced by RunSimulation, loadParameters, verifyDateParameters.
int Simulator::m_maxPositionsPerStock
[TRADING PARAMETERS]
Referenced by loadParameters, openPositions.
int Simulator::m_maxDaysPerPosition
Referenced by loadParameters, makeTrade.
double Simulator::m_stopLoss
Referenced by loadParameters.
bool Simulator::m_dailyPublication
[PUBLICATION PARAMETERS]
Referenced by RunSimulation, initializePublications, loadParameters, recordDailyStatistics, closeDailyPublication.
bool Simulator::m_monthlyPublication
Referenced by RunSimulation, initializePublications, loadParameters, closeMonthlyPublication.
bool Simulator::m_transactionPublication
Referenced by RunSimulation, initializePublications, loadParameters, makeTrade, closePositions, closeTransactionPublication.
bool Simulator::m_signalPublication
Referenced by RunSimulation, initializePublications, loadParameters, recordSignalInfo, closeSignalPublication.
std::ofstream Simulator::m_dailyInfoFile
Output streams to write publications.
Referenced by initializePublications, recordSharpeRatio, recordDailyStatistics, closeDailyPublication.
std::ofstream Simulator::m_monthlyInfoFile
Referenced by RunSimulation, initializePublications, recordMonthlyStatistics, closeMonthlyPublication.
std::ofstream Simulator::m_transactionInfoFile
Referenced by initializePublications, recordTransaction, closeTransactionPublication.
std::ofstream Simulator::m_signalInfoFile
Referenced by initializePublications, recordSignalInfo, closeSignalPublication.
double Simulator::m_ROR
Daily return. The profit for the day divided by the capital committed.
Referenced by RunSimulation, recordDailyStatistics.
double Simulator::m_totalPNL
Cumulative PNL from the beginning of the simulation to the current date.
Referenced by RunSimulation, recordDailyStatistics.
double Simulator::m_dailyPNL
The profit or loss in dollars for the day.
Referenced by RunSimulation, recordDailyStatistics.
double Simulator::m_longPosCount
Daily long position counter variable.
Referenced by RunSimulation, recordDailyStatistics.
double Simulator::m_shortPosCount
Daily short position counter variable.
Referenced by RunSimulation, recordDailyStatistics.
double Simulator::m_totalPosCount
Daily total position counter variable.
Referenced by RunSimulation, recordDailyStatistics.
double Simulator::m_netMarketValue
Total amount of capital committed to the model at the end of the day.
Referenced by RunSimulation, recordDailyStatistics.
double Simulator::m_grossMarketValue
Long capital minus the short capital at the end of the day.
Referenced by RunSimulation, recordDailyStatistics.
DateTime* Simulator::m_today
Date today.
Referenced by RunSimulation, makeTrade, openPositions, closePositions, recordSignalInfo, recordDailyStatistics.
std::vector<double> Simulator::m_dailyPNLRecord
Daily PNL record.
Referenced by RunSimulation.
std::vector<double> Simulator::m_dailyCumulativeROR
Daily cumulative ROR record for all trading stocks in simulation.
Referenced by RunSimulation, calculateSharpeRatio.
std::vector<double> Simulator::m_sharpeRecord
Sharpe ratio record.
Referenced by RunSimulation, calculateSharpeRatio.
int Simulator::m_configFilesPassed
Number of config files passed.
Referenced by Simulator.
int Simulator::m_simulationCount
Count of how many config files have been simulated.
Referenced by Simulator, RunSimulation, initializePublications, recordMonthlyStatistics.
std::vector<const char*> Simulator::m_configFile
Var with config file name.
Referenced by Simulator, StartSimulation.
Config* Simulator::m_config
Configuration object.
Referenced by initializeSimulator, rerunSimulator, checkParameters, loadParameters.
DataAccess* Simulator::m_data
Data access object.
Referenced by RunSimulation, initializeSimulator, initializeTradingTickers, verifyDateParameters.
std::vector<TradingStock*> Simulator::m_tradingStocks
All the trading stocks in the simulation.
Referenced by RunSimulation, rerunSimulator, initializeTradingTickers.
Simulator::Simulator(int argc, const char *argv[])
Main simulator constructor.
Simulator.cpp Implementation of Simulator.h. Created by Salil Maharjan on 4/29/20. Copyright 2020 Salil Maharjan. All rights reserved. Simulator::Simulator Parameterized constructor for Simulator class. Initializes the Simulator. Can handle multiple configuration files. argc int Number of command line arguments. argv const char* Array of command line arguments. Salil Maharjan 5/12/20.
References i, m_configFile, m_configFilesPassed, m_simulationCount.
void Simulator::StartSimulation()
Interface method to start the simulation.
Simulator::StartSimulation Interface method to start the simulation Salil Maharjan 5/12/20.
References i, initializeSimulator, m_configFile, rerunSimulator, RunSimulation.
Referenced by main.
void Simulator::RunSimulation()
Main method to run simulation.
Simulator::RunSimulation Main method to run the simulation. Salil Maharjan 5/12/20.
References calculateSharpeRatio, calculateSignal, CLOSE, closeDailyPublication, closeMonthlyPublication, closeSignalPublication, closeTransactionPublication, TickerData::GetCurrentDataOf, DataAccess::GetTickerData, DataAccess::GetTradingDatesInRange, DataAccess::GetUniverse, m_dailyCumulativeROR, m_dailyPNL, m_dailyPNLRecord, m_dailyPublication, m_data, m_endDate, m_grossMarketValue, m_longPosCount, m_monthlyInfoFile, m_monthlyPublication, m_netMarketValue, m_ROR, m_sharpeRecord, m_shortPosCount, m_signalPublication, m_simulationCount, m_startDate, m_today, m_totalPNL, m_totalPosCount, m_tradingStocks, m_transactionPublication, makeTrade, TickerData::NA_VAL, recordDailyStatistics, recordMonthlyStatistics, recordNoActivity, recordSignalInfo, TickerData::SetTradingDateRange.
Referenced by StartSimulation.
Simulator::Simulator()=default
Private default constructor.
void Simulator::initializeSimulator(const char *a_configFile)
Initializes the simulator by loading configurations, ticker data and trading stocks.
Simulator::initializeSimulator Main method to initialize simulator for run. a_configFile char* Config file to initialize simulator for. Salil Maharjan 5/12/20.
References checkParameters, DataAccess::GetDbInstance, initializePublications, initializeTradingTickers, loadParameters, m_config, m_data, m_tickerPath, m_universePath, verifyDateParameters.
Referenced by StartSimulation.
void Simulator::rerunSimulator(const char *a_configFile)
Rerun simulator for consecutive configuration files.
Simulator::rerunSimulator Rerun simulator for consecutive configuration files a_configFile char* Config file to initialize simulator for. Salil Maharjan 5/12/20.
References checkParameters, initializePublications, initializeTradingTickers, loadParameters, m_config, m_tradingStocks, verifyDateParameters.
Referenced by StartSimulation.
void Simulator::initializePublications()
Initialize file write stream for the publications requested in config.
Simulator::initializePublications Initializes file write streams for the publications requested in configurations. Salil Maharjan 5/12/20.
References m_dailyInfoFile, m_dailyPublication, m_monthlyInfoFile, m_monthlyPublication, m_signalInfoFile, m_signalPublication, m_simulationCount, m_transactionInfoFile, m_transactionPublication.
Referenced by initializeSimulator, rerunSimulator.
bool Simulator::checkParameters()
Checks if all required parameters are passed for simulator to run.
Simulator::checkParameters Checks if all required parameters are passed for simulator to run. bool If all required parameters are in configuration file. Salil Maharjan 5/12/20.
References Config::ContainsParameter, DAILY_PUB_PARAM, DAYS_IN_POS_PARAM, ENTRY_SIGNAL_PARAM, EXIT_SIGNAL_PARAM, m_config, MAX_CAPITAL_PER_STOCK_PARAM, MAX_POS_PER_STOCK, MONTHLY_PUB_PARAM, PERIOD_END_DATE, PERIOD_START_DATE, PORTFOLIO_CAPITAL, SIGNAL_PUB_PARAM, STOP_LOSS_PARAM, TICKER_PATH_PARAM, TRANSACTION_PUB_PARAM, UNIVERSE_PATH_PARAM.
Referenced by initializeSimulator, rerunSimulator.
void Simulator::loadParameters()
Loads parameters required for the simulator.
Simulator::loadParameters Loads parameters from configuration file that are required for the simulation. Salil Maharjan 5/12/20.
References DAILY_PUB_PARAM, DAYS_IN_POS_PARAM, ENTRY_SIGNAL_PARAM, EXIT_SIGNAL_PARAM, Config::GetParameter, m_capitalLimitPerStock, m_config, m_dailyPublication, m_endDate, m_entrySignal, m_exitSignal, m_maxDaysPerPosition, m_maxPositionsPerStock, m_monthlyPublication, m_portfolioCapital, m_signalPublication, m_startDate, m_stopLoss, m_tickerPath, m_transactionPublication, m_universePath, MAX_CAPITAL_PER_STOCK_PARAM, MAX_POS_PER_STOCK, MONTHLY_PUB_PARAM, PERIOD_END_DATE, PERIOD_START_DATE, PORTFOLIO_CAPITAL, SIGNAL_PUB_PARAM, STOP_LOSS_PARAM, TICKER_PATH_PARAM, TRANSACTION_PUB_PARAM, UNIVERSE_PATH_PARAM.
Referenced by initializeSimulator, rerunSimulator.
void Simulator::initializeTradingTickers()
Initialize stocks that the simulator will be trading.
Simulator::initializeTradingTickers Initialize stock tickers from constituents file that the simulator will be trading. Salil Maharjan 5/12/20.
References DataAccess::GetUniverse, m_capitalLimitPerStock, m_data, m_portfolioCapital, m_tradingStocks.
Referenced by initializeSimulator, rerunSimulator.
void Simulator::verifyDateParameters()
Verify date range.
Simulator::verifyDateParameters Verify date range in configuration file to assert if data is available for that range. If not, the simulation will run for all available data instead of stopping. Salil Maharjan 5/12/20.
References DataAccess::CheckDateRange, DataAccess::GetLatestTradingDate, DataAccess::GetOldestTradingDate, m_data, m_endDate, m_startDate.
Referenced by initializeSimulator, rerunSimulator.
double Simulator::calculateSignal(TickerData &a_stockData)
Calculate trade signal.
Simulator::calculateSignal Function to calculate trade signal. Currently uses MACD indicator to get signal. If not, the simulation will run for all available data instead of stopping. a_stockData TickerData& The data of the trading stock in the specified date range. double Trading signal. Salil Maharjan 5/12/20.
References TickerData::GetMACDSignal.
Referenced by RunSimulation.
void Simulator::makeTrade(TradingStock &a_stock, double &a_currentPrice, double &a_signalToday)
Function to open or close positions according to the signal by checking current position.
Simulator::makeTrade Function to make trade according to the signal. a_stock TradingStock& The stock that is being traded. a_currentPrice double& Current price of the stock. a_signalToday double& Signal calculated for the day. Salil Maharjan 5/12/20.
References TradingStock::CheckLongSignal, TradingStock::CheckShortSignal, closePositions, TradingStock::CloseStalePositions, TradingStock::GetSignalRecord, hasEnoughCapital, TradingStock::IsLong, TradingStock::IsShort, m_entrySignal, m_exitSignal, m_maxDaysPerPosition, m_today, m_transactionPublication, openPositions, recordNoActivity, TradingStock::RecordPNL, recordTransaction.
Referenced by RunSimulation.
bool Simulator::hasEnoughCapital(TradingStock &a_stock, double a_price)
Check if available capital for a stock is enough to purchase more equities at a_price.
Simulator::hasEnoughCapital Check if available capital for a stock is enough to purchase more equities at a_price a_stock TradingStock& The stock that is being traded. a_currentPrice double& Current price of the stock. bool If there is sufficient capital to buy positions of a_stock at a_price. Salil Maharjan 5/12/20.
References TradingStock::GetAvailableCapital.
Referenced by makeTrade.
void Simulator::closePositions(TradingStock &a_stock, double &a_currentPrice, double &a_signal)
Close positions for a trading stock.
Simulator::closePositions Method to close positions for a trading stock. a_stock TradingStock& The stock that is being traded. a_currentPrice double& Current price of the stock. a_signalToday double& Signal calculated for the day. Salil Maharjan 5/12/20.
References TradingStock::BuyShares, TradingStock::CloseLongPositions, TradingStock::CloseShortPositions, m_today, m_transactionPublication, TradingStock::RecordPNL, recordTransaction, TradingStock::SellShares, TradingStock::UpdateStockPosition.
Referenced by makeTrade.
void Simulator::openPositions(TradingStock &a_stock, double &a_currentPrice, double &a_signal)
Open positions for a trading stock.
Simulator::openPositions Method to open positions for a trading stock. a_stock TradingStock& The stock that is being traded. a_currentPrice double& Current price of the stock. a_signalToday double& Signal calculated for the day. Salil Maharjan 5/12/20.
References TradingStock::BuyShares, TradingStock::GetAvailableCapital, TradingStock::GetLongSharesHeld, TradingStock::GetShortSharesHeld, m_maxPositionsPerStock, m_today, TradingStock::OpenPosition, Utilities::RoundOff, TradingStock::SellShares, TradingStock::SetLong, TradingStock::SetShort.
Referenced by makeTrade.
void Simulator::recordTransaction(TradingStock &a_stock)
Function to record transactions to a file.
Simulator::recordTransaction Function to record closed transactions to the transaction report file. a_stock TradingStock& The stock that is being traded. Salil Maharjan 5/12/20.
References TradingStock::GetClosedTransactions, TradingStock::GetStockName, TradingStock::GetTransactionCount, i, m_transactionInfoFile.
Referenced by closePositions, makeTrade.
void Simulator::recordSignalInfo(double a_signal)
Function to record signals to a file.
Simulator::recordSignalInfo Function to record signals to a file. a_signal The day's signal Salil Maharjan 5/12/20.
References DateTime::GetASCIIDate, m_signalInfoFile, m_signalPublication, m_today.
Referenced by RunSimulation.
void Simulator::recordDailyStatistics()
Function to record daily statistics to a file.
Simulator::recordDailyStatistics Function to record daily statistics to daily stats file. Salil Maharjan 5/12/20.
References DateTime::Get, DateTime::GetASCIIDate, m_dailyInfoFile, m_dailyPNL, m_dailyPublication, m_grossMarketValue, m_longPosCount, m_netMarketValue, m_ROR, m_shortPosCount, m_today, m_totalPNL, m_totalPosCount, recordSharpeRatio.
Referenced by RunSimulation.
void Simulator::recordMonthlyStatistics()
Function to record monthly statistics to a file.
Simulator::recordMonthlyStatistics Function to record monthly statistics to a file. Uses the generated daily publication to generate a monthly report. Salil Maharjan 5/12/20.
References DateTime::GetMonth, DateTime::GetYear, i, m_monthlyInfoFile, m_simulationCount, Utilities::trimBlanks.
Referenced by RunSimulation.
void Simulator::closeDailyPublication()
Method to close daily publication record file.
Simulator::closeDailyPublication Method to close daily publication record file. Salil Maharjan 5/12/20.
References m_dailyInfoFile, m_dailyPublication.
Referenced by RunSimulation.
void Simulator::closeMonthlyPublication(bool a_flag)
Method to close monthly publication record file.
Simulator::closeMonthlyPublication Method to close monthly publication record file. Monthly statistics use daily statistics, so daily must be set to write monthly publications. a_flag Flag if monthly statistics can be generated. Salil Maharjan 5/12/20.
References m_monthlyInfoFile, m_monthlyPublication.
Referenced by RunSimulation.
void Simulator::closeTransactionPublication()
Method to close transaction publication record file.
Simulator::closeTransactionPublication Method to close transaction publication record file. Salil Maharjan 5/12/20.
References m_transactionInfoFile, m_transactionPublication.
Referenced by RunSimulation.
void Simulator::closeSignalPublication()
Method to close signal publication record file.
Simulator::closeSignalPublication Method to close signal publication record file. Salil Maharjan 5/12/20.
References m_signalInfoFile, m_signalPublication.
Referenced by RunSimulation.
void Simulator::recordSharpeRatio()
Function to record sharpe ratio to daily statistics file.
Simulator::recordSharpeRatio Method to record sharpe ratio to statistics file. Uses calculateSharpeRatio function to calculate sharpe ratio for the entire model. Salil Maharjan 5/12/20.
References calculateSharpeRatio, m_dailyInfoFile.
Referenced by recordDailyStatistics.
void Simulator::recordNoActivity(TradingStock &a_stock)
Method to record necessary elements for no activity (code reuse purposes).
Simulator::recordNoActivity Method to record necessary elements for no activity (code reuse purposes). a_stock TradingStock& The stock that is being traded. Salil Maharjan 5/12/20.
References TradingStock::IncreaseCapitalBy, TradingStock::IncreaseSharesBy, TradingStock::RecordPNL, TradingStock::RecordTransactionsCount.
Referenced by makeTrade, RunSimulation.
double Simulator::calculateSharpeRatio()
Function to calculate sharpe ratio.
Simulator::calculateSharpeRatio Method to calculate sharpe ratio. double Daily sharpe ratio of the model. Salil Maharjan 5/12/20.
References Utilities::GetAverage, Utilities::GetStandardDeviation, m_dailyCumulativeROR, m_sharpeRecord.
Referenced by recordSharpeRatio, RunSimulation.