Config
std::unordered_map<std::string, ConfigValue> Config::m_ConfigData
Map of config values.
Referenced by Load, GetUnaccessedParameters, DisplayParameters, getParameterValue, ClearConfigData.
Config::Config()
Default constructor.
Config::Config(const char *a_file)
Main class constructor.
References Load.
virtual Config::~Config()
Virtual deconstructor.
bool Config::GetParameter(std::string a_parameter, T &a_value)
Template function to access parameters.
Config::GetParameter Template function to get parameter value and pass it by reference. Template supports: (string, int, short, long, float, double) Explicit instantiation of template function on header file to prevent linker error. Separate template function specialization functions defined for (bool, char*) a_parameter string Parameter name. a_value T Variable to save parameter value. Template supported types. bool Function execution status. Salil Maharjan 4/30/20.
References getParameterValue.
Referenced by Simulator::loadParameters.
bool Config::GetParameter(std::string a_parameter, char *a_value)
Template function specializations to access parameters as char* and bool.
Config::GetParameter Template function specialization of function (GetParameter) for returning parameter value as char*. a_parameter string Parameter name. a_value char* Variable to save parameter value. bool Function execution status. Salil Maharjan 4/30/20.
References getParameterValue.
bool Config::GetParameter(std::string a_parameter, bool &a_value)
Config::GetParameter Template function specialization of function (GetParameter) for returning parameter value as booleans. a_parameter string Parameter name. a_value bool Variable to save parameter value. bool Function execution status. Salil Maharjan 4/30/20.
References getParameterValue.
bool Config::Load(const char *a_file, bool a_displayParameters=true)
Load in data from a specified configuration file. Allows multiple calls.
Config.cpp Implementation of Config.h. Created by Salil Maharjan on 4/25/20. Copyright © 2020 Salil Maharjan. All rights reserved. Config::Load Method to load configuration file. Uses parseLine method to parse lines. a_file char* Config file name. a_displayParameters bool Flag for display purposes bool Function execution status. Salil Maharjan 4/30/20.
References DisplayParameters, m_ConfigData, parseLine, Config::ConfigValue::value.
Referenced by Config.
bool Config::ContainsParameter(std::string a_parameter)
Test if a config file has a parameter for a given segment.
References getParameterValue.
Referenced by Simulator::checkParameters.
void Config::GetUnaccessedParameters(std::vector< std::string > &a_paramNames)
Provides a list of the parameters that were not accessed.
Config::GetUnaccessedParameters Method to provide the list of the parameters that were not accessed. a_paramNames vector<string> Names of parameters that were not accessed. Salil Maharjan 4/30/20.
References m_ConfigData.
void Config::ClearConfigData()
Clear the set of recorded parameters.
References m_ConfigData.
void Config::DisplayParameters()
Display the parameters in alphabetical order.
Config::DisplayParameters Method to display the parameters in alphabetical order. Salil Maharjan 4/30/20.
References m_ConfigData.
Referenced by Load.
void Config::trimBlanks(std::string &a_str)
Trim leading and trailing blanks.
Config::trimBlanks Method to trim leading and trailing whitespaces. a_str string Reference to string to trim white spaces. Salil Maharjan 4/30/20.
Referenced by parseLine.
bool Config::parseLine(const std::string &a_line, std::string &a_name, std::string &a_value)
Get parameters by parsing line from config file.
Config::parseLine Method to parse configuration file line into parameter name and value. a_line string The line read from configuration file. a_name string Variable to save parameter name by reference.
References trimBlanks.
Referenced by Load.
bool Config::getParameterValue(std::string a_name, std::string &a_value)
Get the value of a specified parameter.
Config::getParameterValue Private utility function to get parameter value as a string. Used by GetParameter. a_name string Parameter name. a_value bool Parameter value. bool Function execution status. Salil Maharjan 4/30/20.
References m_ConfigData.
Referenced by ContainsParameter, GetParameter.