TradingStock
std::string TradingStock::m_tickerName
Ticker name.
Referenced by GetStockName.
double TradingStock::m_availableCapital
Available capital for trading stock.
Referenced by IncreaseCapitalBy, DecreaseCapitalBy, GetAvailableCapital.
int TradingStock::m_transactionsTotalCount
Total transactions count.
Referenced by TradingStock, RecordTransactionsCount, GetTransactionCount.
int TradingStock::m_transactionCounter
Current complete transaction counter.
Referenced by TradingStock, GetTransactionCount.
double TradingStock::m_totalSharesCount
Total shares held for stock.
Referenced by TradingStock, SellShares, BuyShares, IncreaseSharesBy, DecreaseSharesBy, GetTotalShares.
bool TradingStock::m_longPosFlag
Long position flag.
Referenced by TradingStock, UpdateStockPosition, IsLong, SetLong.
bool TradingStock::m_shortPosFlag
Short position flag.
Referenced by TradingStock, UpdateStockPosition, IsShort, SetShort.
std::vector<Transaction*> TradingStock::m_transactions
Records all transactions.
Referenced by OpenPosition, CloseLongPositions, CloseShortPositions, CheckShortSignal, CheckLongSignal, UpdateStockPosition, CloseStalePositions, GetShortSharesHeld, GetLongSharesHeld, GetShortCapital, GetLongCapital, GetClosedTransactions, newTradingDay.
std::vector<double> TradingStock::m_signalActivityRecord
Records daily signals.
Referenced by RecordSignal, GetSignalRecord.
std::vector<double> TradingStock::m_capitalActivityRecord
Records daily capital activities.
Referenced by IncreaseCapitalBy, DecreaseCapitalBy, GetInvestedCapital.
std::vector<double> TradingStock::m_shareActivityRecord
Records daily position changes.
Referenced by SellShares, BuyShares, IncreaseSharesBy, DecreaseSharesBy, GetLatestShareActivity.
std::vector<double> TradingStock::m_dailyPNLRecord
Records daily PNL.
Referenced by RecordPNL, CloseStalePositions, GetDailyPnL.
std::vector<double> TradingStock::m_dailyReturnRecord
Records daily rate of return (ROR)
Referenced by RecordDailyReturn, CloseStalePositions, CalculateDailySharpeRatio, GetDailyROR, GetROR.
std::vector<double> TradingStock::m_cumulativePNLRecord
Records daily cumulative PNL.
Referenced by RecordPNL, CloseStalePositions.
std::vector<int> TradingStock::m_TransactionsCountRecord
Records daily transaction counts.
Referenced by RecordTransactionsCount.
std::vector<double> TradingStock::m_sharpeRatioRecord
Records daily sharpe ratio.
Referenced by CalculateDailySharpeRatio, GetSharpeToday.
TradingStock::TradingStock(std::string a_tickerName, double a_startingCapital)
Class parameterized constructor.
TradingStock.cpp Implementation of TradingStock.h Created by Salil Maharjan on 05/03/20. Copyright © 2020 Salil Maharjan. All rights reserved. TradingStock::TradingStock Class parameterized constructor to create a trading stock object. a_tickerName string Trading stock's ticker name. a_startingCapital double Initial capital to invest for the stock. Salil Maharjan 5/14/20.
References m_longPosFlag, m_shortPosFlag, m_totalSharesCount, m_transactionCounter, m_transactionsTotalCount.
const std::string TradingStock::GetStockName()
References m_tickerName.
Referenced by Simulator::recordTransaction.
const bool TradingStock::IsLong()
References m_longPosFlag.
Referenced by Simulator::makeTrade.
const bool TradingStock::IsShort()
References m_shortPosFlag.
Referenced by Simulator::makeTrade.
const std::vector<double> TradingStock::GetSignalRecord()
References m_signalActivityRecord.
Referenced by Simulator::makeTrade.
const double TradingStock::GetTotalShares()
References m_totalSharesCount.
const double TradingStock::GetAvailableCapital()
References m_availableCapital.
Referenced by Simulator::hasEnoughCapital, Simulator::openPositions.
const double TradingStock::GetDailyPnL()
References m_dailyPNLRecord.
const double TradingStock::GetDailyROR()
References m_dailyReturnRecord.
const std::vector<double> TradingStock::GetROR()
References m_dailyReturnRecord.
const double TradingStock::GetLatestShareActivity()
References m_shareActivityRecord.
const double TradingStock::GetSharpeToday()
TradingStock::GetSharpeToday Accessor method to get the Sharpe ratio of the current day of an individual stock. Salil Maharjan 5/14/20.
References m_sharpeRatioRecord.
double TradingStock::GetTransactionCount()
Method to get current completed transaction count (Does not consider incomplete transactions.)
TradingStock::GetTransactionCount Function to get current closed transaction counter. double Number of current completed transactions. Salil Maharjan 5/14/20.
References m_transactionCounter, m_transactionsTotalCount.
Referenced by Simulator::recordTransaction.
const double TradingStock::GetShortSharesHeld()
Method to get short shares held.
TradingStock::GetShortSharesHeld Accessor method to get short shares held in the trading stock. double Number of short positions held. Salil Maharjan 5/14/20.
References i, m_transactions.
Referenced by Simulator::openPositions.
const double TradingStock::GetLongSharesHeld()
Method to get long shares held.
TradingStock::GetLongSharesHeld Accessor method to get long shares held in the trading stock. double Number of short positions held. Salil Maharjan 5/14/20.
References i, m_transactions.
Referenced by Simulator::openPositions.
std::vector< Transaction * > TradingStock::GetClosedTransactions()
Method to get closed transactions and remove them from memory.
TradingStock::GetClosedTransactions Method to get closed transactions. Once returned, they are removed from the record. double Total capital in long positions. Salil Maharjan 5/14/20.
References i, m_transactions.
Referenced by Simulator::recordTransaction.
const double TradingStock::GetShortCapital()
Method to get short capital in investment.
TradingStock::GetShortCapital Accessor method to get capital invested in short positions in trading stock. double Total capital in short positions. Salil Maharjan 5/14/20.
References i, m_transactions.
const double TradingStock::GetLongCapital()
Method to get long capital in investment.
TradingStock::GetLongCapital Accessor method to get capital invested in long positions in trading stock. double Total capital in long positions. Salil Maharjan 5/14/20.
References i, m_transactions.
void TradingStock::SetLong(bool a_long)
References m_longPosFlag.
Referenced by Simulator::openPositions.
void TradingStock::SetShort(bool a_short)
References m_shortPosFlag.
Referenced by Simulator::openPositions.
void TradingStock::IncreaseSharesBy(double a_share)
TradingStock::IncreaseSharesBy Function to increase shares owned in the stock. a_share double Number of shares to add. Salil Maharjan 5/14/20.
References m_shareActivityRecord, m_totalSharesCount.
Referenced by Simulator::recordNoActivity.
void TradingStock::DecreaseSharesBy(double a_share)
TradingStock::DecreaseSharesBy Function to decrease shares owned in the stock. a_share double Number of shares to remove. Salil Maharjan 5/14/20.
References m_shareActivityRecord, m_totalSharesCount.
void TradingStock::IncreaseCapitalBy(double a_share)
TradingStock::IncreaseCapitalBy Function to increase available capital in the stock and record it. a_capital double Capital to increase. Salil Maharjan 5/14/20.
References m_availableCapital, m_capitalActivityRecord.
Referenced by Simulator::recordNoActivity, SellShares.
void TradingStock::DecreaseCapitalBy(double a_share)
TradingStock::DecreaseCapitalBy Function to decrease available capital in the stock and record it. a_capital double Capital to decrease. Salil Maharjan 5/14/20.
References m_availableCapital, m_capitalActivityRecord.
Referenced by BuyShares.
void TradingStock::SellShares(double a_shares, double a_price)
Method to sell shares.
TradingStock::SellShares Method to sell shares. Updates capital and record variables. a_shares double Number of shares to sell. a_price double Price at which to sell shares. Salil Maharjan 5/14/20.
References IncreaseCapitalBy, m_shareActivityRecord, m_totalSharesCount.
Referenced by Simulator::closePositions, CloseStalePositions, Simulator::openPositions.
void TradingStock::BuyShares(double a_shares, double a_price)
Method to buys shares.
TradingStock::BuyShares Method to buy shares. Updates capital and record variables. a_shares double Number of shares to buy. a_price double Price at which to buy shares. Salil Maharjan 5/14/20.
References DecreaseCapitalBy, m_shareActivityRecord, m_totalSharesCount.
Referenced by Simulator::closePositions, CloseStalePositions, Simulator::openPositions.
void TradingStock::CloseStalePositions(int a_dayLimit, DateTime *a_date, double a_signal, double a_price)
Method to close positions that exceed maximum days limit.
TradingStock::CloseStalePositions Method to close positions that exceed maximum days limit. a_dayLimit int Maximum days in position limit. a_date DateTime* Today's date. a_signal double Current day's signal. a_price double Current price of shares. Salil Maharjan 5/14/20.
References BuyShares, i, m_cumulativePNLRecord, m_dailyPNLRecord, m_dailyReturnRecord, m_transactions, RecordTransactionsCount, SellShares, UpdateStockPosition.
Referenced by Simulator::makeTrade.
void TradingStock::OpenPosition(DateTime *a_date, double a_signal, double a_share, double a_price)
Method to open a position for the trading stock.
TradingStock::OpenPosition Open a new position for the trading stock. a_date DateTime* Today's date. a_signal double Current day's signal. a_share double Number of shares to open. a_price double Price of shares at the time of opening. Salil Maharjan 5/14/20.
References m_transactions.
Referenced by Simulator::openPositions.
double TradingStock::CloseLongPositions(DateTime *a_date, double a_signal, double a_price, double &a_investedCaptial, double &a_numOfShares)
Method to close all long positions.
TradingStock::CloseLongPositions Method to close profiting long positions. Returns profit/loss generated from closing long positions. Updates invested capital in closing long positions and number of long positions that are variables passed by reference. a_date DateTime* Today's date. a_signal double Current day's signal. a_price double Price of shares at the time of closing. a_investedCaptial double& Invested capital placeholder to return the invested capital in long positions. a_numOfShares double& Placeholder to return number of shares in long position that were closed. double Profit or loss generated from closing long positions. Salil Maharjan 5/14/20.
References i, m_transactions, RecordTransactionsCount.
Referenced by Simulator::closePositions.
double TradingStock::CloseShortPositions(DateTime *a_date, double a_signal, double a_price, double &a_investedCaptial, double &a_numOfShares)
Method to close all short positions.
TradingStock::CloseShortPositions Method to close profiting short positions. Returns profit/loss generated from closing short positions. Updates invested capital in closing short positions and number of short positions that are variables passed by reference. a_date DateTime* Today's date. a_signal double Current day's signal. a_price double Price of shares at the time of closing. a_investedCaptial double& Invested capital placeholder to return the invested capital in long positions. a_numOfShares double& Placeholder to return number of shares in long position that were closed. double Profit or loss generated from closing long positions. Salil Maharjan 5/14/20.
References i, m_transactions, RecordTransactionsCount.
Referenced by Simulator::closePositions.
bool TradingStock::CheckShortSignal(double a_price)
Method to check if signal is profitable for short positions.
TradingStock::CheckShortSignal Method to check if signal is profitable for short positions. a_price double Current price of shares. bool If signal will be profitable. Salil Maharjan 5/14/20.
References i, m_transactions.
Referenced by Simulator::makeTrade.
bool TradingStock::CheckLongSignal(double a_price)
Method to check if signal is profitable for long positions.
TradingStock::CheckLongSignal Method to check if signal is profitable for long positions. a_price double Current price of shares. bool If signal will be profitable. Salil Maharjan 5/14/20.
References i, m_transactions.
Referenced by Simulator::makeTrade.
void TradingStock::UpdateStockPosition()
Method to update long/short position status of the trading stock.
TradingStock::UpdateStockPosition Method to update long/short position flags of the trading stock. Salil Maharjan 5/14/20.
References i, m_longPosFlag, m_shortPosFlag, m_transactions.
Referenced by Simulator::closePositions, CloseStalePositions.
void TradingStock::RecordSignal(double a_signal)
Record day's signal.
TradingStock::RecordSignal Function to record the trading day signal and update the days in position of the stocks held. a_signal double Day's trading signal. Salil Maharjan 5/14/20.
References m_signalActivityRecord, newTradingDay.
void TradingStock::RecordPNL(double a_pnl, double a_investedCapital)
Record day's PNL.
TradingStock::RecordPNL Records PNL and calls RecordDailyReturn to record ROR. (coupled functions) a_pnl double Profit or loss for the day. a_investedCapital double Invested capital in the position generating profit or loss. Salil Maharjan 5/14/20.
References m_cumulativePNLRecord, m_dailyPNLRecord, RecordDailyReturn.
Referenced by Simulator::closePositions, Simulator::makeTrade, Simulator::recordNoActivity.
void TradingStock::RecordTransactionsCount(int a_count)
Record day's number of transactions.
TradingStock::RecordTransactionsCount Record daily transaction count. a_count int Daily transactions count. Salil Maharjan 5/14/20.
References m_TransactionsCountRecord, m_transactionsTotalCount.
Referenced by CloseLongPositions, CloseShortPositions, CloseStalePositions, Simulator::recordNoActivity.
void TradingStock::RecordDailyReturn(double a_amount)
Recard day's daily return.
TradingStock::RecordDailyReturn Record daily rate of return (ROR). a_amount double Daily ROR. Salil Maharjan 5/14/20.
References m_dailyReturnRecord.
Referenced by RecordPNL.
double TradingStock::GetInvestedCapital()
Get latest committed capital in an investment.
TradingStock::GetInvestedCapital Get latest committed capital in an investment double Latest committed capital activity. Salil Maharjan 5/14/20.
References m_capitalActivityRecord.
void TradingStock::CalculateDailySharpeRatio()
Calculate daily sharpe ratio for individual stock.
TradingStock::CalculateDailySharpeRatio Calculate daily sharpe ratio for individual stock. Can be used to get individual stock's Sharpe ratio instead of the complete model's Sharpe. Salil Maharjan 5/14/20.
References Utilities::GetAverage, Utilities::GetStandardDeviation, m_dailyReturnRecord, m_sharpeRatioRecord.
TradingStock::TradingStock()=default
Private default constructor.
void TradingStock::newTradingDay()
Method to update days in position of all held shares.
TradingStock::newTradingDay Method to update days in position of all held shares Salil Maharjan 5/14/20.
References i, m_transactions.
Referenced by RecordSignal.