DateTime
DAY_OF_WEEK
const int DateTime::BlankDate
int DateTime::m_date
Date stored as ( year * 10000 + 100 * month + day )
Referenced by Set, SetToday, SetActualToday, operator=, DateTime, GetYear, GetMonth, GetDay, Get, GetASCIIDate, GetDayOfWeek, isLeapYear, getJulianDay, operator int, dateOffset.
int DateTime::m_FakeTodayValue
Fake date value of today.
DateTime.cpp Implementation of DateTime.hpp Created by Salil Maharjan on 3/22/20. Copyright © 2020 Salil Maharjan. All rights reserved.
Referenced by SetToday, setFakeTodayValue.
int DateTime::dayPreMonth[13]
The number of days since the beginning of the year to a given month. (non-leap year)
Referenced by getJulianDay.
int DateTime::daysInMonth[13]
The number of days in a month. (non-leap year)
Referenced by reverseOffset.
DateTime::DateTime()
Default constructor.
References m_date.
Referenced by operator!=, operator<, operator<=, operator==, operator>, operator>=.
DateTime::DateTime(int a_year, int a_month, int a_day)
General date format parameterized constructor (YYYY MM DD)
References Set.
DateTime::DateTime(int a_date)
Internal date format parameterized constructor.
References Set.
DateTime::DateTime(const DateTime &a_date)
Copy constructor.
References Set.
int DateTime::GetYear() const
References m_date.
Referenced by Get, Simulator::recordMonthlyStatistics.
int DateTime::GetMonth() const
References m_date.
Referenced by Get, Simulator::recordMonthlyStatistics.
int DateTime::GetDay() const
References m_date.
Referenced by Get.
int DateTime::Get() const
Gets the date as one value.
References m_date.
Referenced by Simulator::recordDailyStatistics, Set.
void DateTime::Get(int &a_year, int &a_month, int &a_day) const
Gets the date as component values.
References GetDay, GetMonth, GetYear.
std::string DateTime::GetASCIIDate()
Get date as an ASCII string in format "MM/DD/YYYY".
References m_date.
Referenced by Simulator::recordDailyStatistics, Simulator::recordSignalInfo, TickerData::SetTradingDateRange.
int DateTime::GetDayOfWeek() const
Gets the Day of the week as integral value.
References getJulianDay, m_date.
void DateTime::Set(int a_year, int a_month, int a_day)
DateTime::Set Date set function for General date format parameterized constructor (YYYY MM DD) a_year int Year a_month int Month a_day int Date Salil Maharjan 3/22/20.
References checkDateValueRanges, m_date.
Referenced by DateTime, operator++, operator--, reverseOffset.
void DateTime::Set(int a_date)
DateTime::Set Date set function for Internal date format parameterized constructor a_date int Date passed in internal format YYYYMMDD Salil Maharjan 3/24/20.
References checkDateValueRanges, m_date.
void DateTime::Set(const DateTime &a_date)
References Get, m_date.
bool DateTime::checkDateValueRanges(int a_year, int a_month, int a_day)
Function to assert date value ranges.
DateTime::checkDateValueRanges Function to assert date value ranges a_year int Year a_month int Month a_day int Date bool If passed values mark a valid date. Salil Maharjan 3/24/20.
Referenced by operator=, Set.
void DateTime::SetToday()
Record today's local date in this object - uses faked today's date if set.
DateTime::SetToday Record today's local date in this object - uses faked today's date if set. Salil Maharjan 5/12/20.
References m_date, m_FakeTodayValue, SetActualToday.
void DateTime::SetActualToday()
Record today's local date in this object. Does not use faked today's date.
DateTime::SetToday Record today's local date in this object. Does not use faked today's date. Salil Maharjan 5/12/20.
References m_date.
Referenced by SetToday.
bool DateTime::isLeapYear() const
Determines if the year recorded here is a leap year.
References m_date.
Referenced by getJulianDay.
int DateTime::getJulianDay() const
Gets the Julian day from this date. Julian day vary from 0 to 365.
References dayPreMonth, isLeapYear, m_date.
Referenced by dateOffset, GetDayOfWeek.
int DateTime::CalendarDiffDates(const DateTime &a_nearDate, const DateTime &a_farDate)
Computes the calendar difference between two date.
References dateOffset.
Referenced by operator-.
DateTime::operator int() const
Conversion operators.
References m_date.
DateTime& DateTime::operator=(const DateTime &a_date)
Assignment operators.
References m_date.
DateTime & DateTime::operator=(int a_date)
DateTime::operator = Assignment operator overload. a_date DateTime DateTime object to assign. DateTime& New DateTime that is assigned. Salil Maharjan 5/12/20.
References checkDateValueRanges, m_date.
int DateTime::operator-(const DateTime &a_date)
Finds the difference between two dates.
References CalendarDiffDates.
DateTime DateTime::operator-(int a_days)
Subtracts a specified number of days to the date.
References dateOffset, reverseOffset.
DateTime DateTime::operator+(int a_days)
Adds a specified number of days to the date.
References dateOffset, reverseOffset.
bool DateTime::operator==(const DateTime &a_date)
Comparison operator to compare two dates:
References dateOffset.
bool DateTime::operator==(int a_date)
References dateOffset, DateTime.
bool DateTime::operator!=(const DateTime &a_date)
References dateOffset.
bool DateTime::operator!=(int a_date)
References dateOffset, DateTime.
bool DateTime::operator<(const DateTime &a_date)
References dateOffset.
bool DateTime::operator<(int a_date)
References dateOffset, DateTime.
bool DateTime::operator<=(const DateTime &a_date)
References dateOffset.
bool DateTime::operator<=(int a_date)
References dateOffset, DateTime.
bool DateTime::operator>(const DateTime &a_date)
References dateOffset.
bool DateTime::operator>(int a_date)
References dateOffset, DateTime.
bool DateTime::operator>=(const DateTime &a_date)
References dateOffset.
bool DateTime::operator>=(int a_date)
References dateOffset, DateTime.
DateTime& DateTime::operator--()
Unary minus operators. (PREFIX)
References dateOffset, reverseOffset, Set.
Referenced by operator--.
DateTime DateTime::operator--(int)
Unary minus operators. (POSTFIX)
References d, operator--.
DateTime& DateTime::operator++()
Unary plus operators. (PREFIX)
References dateOffset, reverseOffset, Set.
Referenced by operator++.
DateTime DateTime::operator++(int)
Unary plus operators. (POSTFIX)
References d, operator++.
static std::string DateTime::GetStringDOW(DAY_OF_WEEK a_dow)
Get day of the week as a string.
References int, UNDEF_DOW.
static void DateTime::setFakeTodayValue(int a_val)
Set the fake today value. This will be used instead of the real today.
References m_FakeTodayValue.
int DateTime::dateOffset(const DateTime &a_date)
Get the offset from the year 0.
References getJulianDay, m_date.
Referenced by CalendarDiffDates, operator!=, operator+, operator++, operator-, operator--, operator<, operator<=, operator==, operator>, operator>=.
DateTime DateTime::reverseOffset(int a_days)
Reverse date offset.
DateTime::reverseOffset Reverse date offset a_days int Number of days to reverse offset. DateTime The date after reversing a_days offset. Salil Maharjan 5/12/20.
References daysInMonth, Set.
Referenced by operator+, operator++, operator-, operator--.