DataAccess
const std::string DataAccess::m_tradingDatesRefTicker
TickerData for referencing trading dates. Uses IBM.
Referenced by loadTradingDates, loadTickerData.
DataAccess * DataAccess::m_dataInstance
Single DataAccess instance var.
DataAccess.cpp Implementation of DataAccess.h Created by Salil Maharjan on 4/29/20. Copyright © 2020 Salil Maharjan. All rights reserved.
Referenced by GetDbInstance.
std::vector< std::string > DataAccess::m_tickerNames
TickerData names specified in the universe.
Referenced by loadTickerNames, loadTickerData, GetUniverse.
std::vector< DateTime * > DataAccess::m_tradingDates
Trading dates loaded from reference ticker.
Referenced by CheckDateRange, GetTradingDatesInRange, loadTradingDates, GetTradingDates, GetOldestTradingDate, GetLatestTradingDate.
std::map< std::string, TickerData * > DataAccess::m_tickerData
Map variable ( TickerData Name : TickerData Data )
Referenced by GetTickerData, loadTickerData.
const std::vector<std::string> DataAccess::GetUniverse()
Get constituent names in the universe.
References m_tickerNames.
Referenced by Simulator::initializeTradingTickers, Simulator::RunSimulation.
const std::vector<DateTime*> DataAccess::GetTradingDates()
Get trading dates.
References m_tradingDates.
DateTime* DataAccess::GetOldestTradingDate()
Get oldest trading date for which data is available.
References m_tradingDates.
Referenced by Simulator::verifyDateParameters.
DateTime* DataAccess::GetLatestTradingDate()
Get most recent trading date for which data is available.
References m_tradingDates.
Referenced by Simulator::verifyDateParameters.
std::vector< DateTime * > DataAccess::GetTradingDatesInRange(DateTime *a_from, DateTime *a_to)
Get trading dates from "a_from" to "a_to".
DataAccess::GetTradingDatesInRange. Get trading dates from "a_from" to "a_to" according to reference ticker. IBM. a_from DateTime* Starting date range. a_to DateTime* End of date range. vector<DateTime*> All trading dates in range. Salil Maharjan 4/29/20.
References i, m_tradingDates.
Referenced by Simulator::RunSimulation.
TickerData * DataAccess::GetTickerData(std::string a_ticker)
Get TickerData Data.
DataAccess::GetTickerData. Get ticker data for a_ticker. a_ticker string The name of the ticker to get data. TickerData* Price data of a_ticker Salil Maharjan 4/29/20.
References m_tickerData.
Referenced by Simulator::RunSimulation.
DataAccess::~DataAccess()=default
Destructor.
bool DataAccess::CheckDateRange(DateTime *a_startDate, DateTime *a_endDate)
Check date range with available data's date range.
DataAccess::CheckDateRange. Check date range with available data's date range. a_startDate DateTime* Starting date range. a_endDate DateTime* End of date range. bool If data is available for the date range. Salil Maharjan 4/29/20.
References m_tradingDates.
Referenced by Simulator::verifyDateParameters.
DataAccess * DataAccess::GetDbInstance(const std::string a_directory, const std::string a_universe)
Static access method to create a singleton DataAccess object.
DataAccess::GetDbInstance. Method to create a single instance of DataAccess and prevent multiple instances. a_directory string Price data directory path. a_universe string Directory path for file with ticker name universe. DataAccess* Single instance of the path. Salil Maharjan 4/29/20.
References DataAccess, m_dataInstance.
Referenced by Simulator::initializeSimulator.
DataAccess::DataAccess()
Private constructors to prevent multiple instancing:
Referenced by GetDbInstance.
DataAccess::DataAccess(const std::string &a_directory, const std::string &a_universe)
Main class parameterized constructor.
DataAccess::DataAccess. Constructor to create single instance of DataAccess. Stores price data for the specified universe in memory. a_directory string Price data directory path. a_universe string Directory path for ticker name universe file. Salil Maharjan 4/29/20.
References loadTickerData, loadTickerNames.
DataAccess::DataAccess(DataAccess const &)
Private copy constructor.
DataAccess& DataAccess::operator=(DataAccess const &)=delete
Delete assignment operator.
void DataAccess::loadTickerNames(const std::string &a_universe)
Method to load ticker names from the constituent universe file.
DataAccess::loadTickerNames. Method to load ticker names in the universe. a_universe string Directory path for ticker name universe file. Salil Maharjan 4/29/20.
References m_tickerNames.
Referenced by DataAccess.
void DataAccess::loadTickerData(const std::string &a_directory)
Method to load price data for loaded tickers.
DataAccess::loadTickerData. Method to load price data for each ticker in the universe. a_directory string Price data directory path. Salil Maharjan 4/29/20.
References i, loadTradingDates, m_tickerData, m_tickerNames, m_tradingDatesRefTicker.
Referenced by DataAccess.
void DataAccess::loadTradingDates(const std::string &a_directory)
Method to load trading dates from the refence ticker, IBM.
DataAccess::loadTradingDates. Method to load trading dates from the refence ticker, IBM. a_directory string Price data directory path. Salil Maharjan 4/29/20.
References m_tradingDates, m_tradingDatesRefTicker.
Referenced by loadTickerData.