Utilities
int Utilities::RoundOff(double a_value)
Function to round off value to the lower integral value.
Utilities.cpp Implementation of Utilities.h. Created by Salil Maharjan on 5/04/20. Copyright © 2020 Salil Maharjan. All rights reserved. Utilities::RoundOff Function to round off value to integer value. Uses floor. a_value double Value to round off. int Integral value of a_value left rounded. Salil Maharjan 5/04/20.
Referenced by Simulator::openPositions.
double Utilities::GetAverage(std::vector< double > a_list)
Function to get average of a list with doubles.
Utilities::GetAverage Function to get average of a list with doubles. a_list vector<double> List of doubles double The mean of the list. Salil Maharjan 5/04/20.
Referenced by TradingStock::CalculateDailySharpeRatio, Simulator::calculateSharpeRatio.
double Utilities::GetStandardDeviation(std::vector< double > a_list, double a_average)
Function to get the standard deviation of a list with doubles.
Utilities::GetStandardDeviation Function to get the standard deviation of a list with doubles. a_list vector<double> List of doubles. a_average double The mean of the list. double The standard deviation of the list. Salil Maharjan 5/04/20.
Referenced by TradingStock::CalculateDailySharpeRatio, Simulator::calculateSharpeRatio.
void Utilities::trimBlanks(std::string &a_str)
Method to trim leading and trailing blanks while reading data.
Utilities::trimBlanks Method to trim leading and trailing whitespaces. a_str string Reference to string to trim white spaces. Salil Maharjan 4/30/20.
Referenced by TickerData::parseTickerData, Simulator::recordMonthlyStatistics.