.TH "Config::ConfigValue" 3 "Sat Jun 6 2020" "Version Version 1.0" "DOROTHY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config::ConfigValue \- Struct to hold configuration values and access flag\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigValue\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBisAccessed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct to hold configuration values and access flag\&. 
.PP
Definition at line 77 of file Config\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Config::ConfigValue::ConfigValue ()\fC [inline]\fP"

.PP
Definition at line 83 of file Config\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Config::ConfigValue::isAccessed"

.PP
Definition at line 81 of file Config\&.h\&.
.SS "std::string Config::ConfigValue::value"

.PP
Definition at line 79 of file Config\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DOROTHY from the source code\&.
