.TH "Config.h" 3 "Sat Jun 6 2020" "Version Version 1.0" "DOROTHY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config.h
.SH SYNOPSIS
.br
.PP
\fC#include 'PrefixHeader\&.pch'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfig\fP"
.br
.ti -1c
.RI "struct \fBConfig::ConfigValue\fP"
.br
.RI "Struct to hold configuration values and access flag\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DOROTHY from the source code\&.
