.TH "main.cpp" 3 "Sat Jun 6 2020" "Version Version 1.0" "DOROTHY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Simulator\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP argc, const \fBchar\fP *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBint\fP argc, const \fBchar\fP * argv[])"
\fBmain\&.cpp\fP Main entry point for Dorothy financial simulator\&.
.PP
Created by Salil Maharjan on 3/22/20\&. Copyright © 2020 Salil Maharjan\&. All rights reserved\&. 
.PP
Definition at line 15 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DOROTHY from the source code\&.
