.TH "cmake-build-debug/CMakeFiles/TargetDirectories.txt" 3 "Sat Jun 6 2020" "Version Version 1.0" "DOROTHY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake-build-debug/CMakeFiles/TargetDirectories.txt
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for DOROTHY from the source code\&.
