.TH "TickerData.h" 3 "Sat Jun 6 2020" "Version Version 1.0" "DOROTHY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TickerData.h
.SH SYNOPSIS
.br
.PP
\fC#include 'PrefixHeader\&.pch'\fP
.br
\fC#include 'DateTime\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTickerData\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTICKER_FIELDS\fP { \fBOPEN\fP, \fBSTART_TICKER_FIELDS\fP = OPEN, \fBDATA_FIELD_START\fP = OPEN, \fBHIGH\fP, \fBLOW\fP, \fBCLOSE\fP, \fBVOLUME\fP, \fBADJ_CLOSE\fP, \fBDIVIDEND\fP, \fBSPLIT\fP, \fBVWAP\fP, \fBSHARE_OUTSTANDING\fP, \fBDATA_FIELD_END\fP = SHARE_OUTSTANDING, \fBFAST_EMA\fP, \fBSLOW_EMA\fP, \fBMACD_LINE\fP, \fBSIG_LINE\fP, \fBMACD_HIST\fP, \fBEND_TICKER_FIELDS\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBTICKER_FIELDS\fP"
\fBTickerData\&.h\fP Handles ticker data for the trading stocks\&.
.PP
Created by Salil Maharjan on 4/30/20\&. Copyright © 2020 Salil Maharjan\&. All rights reserved\&. ENUM of Ticker fields as found in the Ticker data source file\&. Includes computed fields used in the simulation 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOPEN \fP\fP
.TP
\fB\fISTART_TICKER_FIELDS \fP\fP
.TP
\fB\fIDATA_FIELD_START \fP\fP
.TP
\fB\fIHIGH \fP\fP
.TP
\fB\fILOW \fP\fP
.TP
\fB\fICLOSE \fP\fP
.TP
\fB\fIVOLUME \fP\fP
.TP
\fB\fIADJ_CLOSE \fP\fP
.TP
\fB\fIDIVIDEND \fP\fP
.TP
\fB\fISPLIT \fP\fP
.TP
\fB\fIVWAP \fP\fP
.TP
\fB\fISHARE_OUTSTANDING \fP\fP
.TP
\fB\fIDATA_FIELD_END \fP\fP
.TP
\fB\fIFAST_EMA \fP\fP
.TP
\fB\fISLOW_EMA \fP\fP
.TP
\fB\fIMACD_LINE \fP\fP
.TP
\fB\fISIG_LINE \fP\fP
.TP
\fB\fIMACD_HIST \fP\fP
.TP
\fB\fIEND_TICKER_FIELDS \fP\fP
.PP
Definition at line 22 of file TickerData\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DOROTHY from the source code\&.
