.TH "Transaction.h" 3 "Sat Jun 6 2020" "Version Version 1.0" "DOROTHY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transaction.h
.SH SYNOPSIS
.br
.PP
\fC#include 'PrefixHeader\&.pch'\fP
.br
\fC#include 'DateTime\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransaction\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DOROTHY from the source code\&.
