.TH "Utilities.h" 3 "Sat Jun 6 2020" "Version Version 1.0" "DOROTHY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utilities.h
.SH SYNOPSIS
.br
.PP
\fC#include 'PrefixHeader\&.pch'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUtilities\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBUtilities::RoundOff\fP (double a_value)"
.br
.RI "Function to round off value to the lower integral value\&. "
.ti -1c
.RI "double \fBUtilities::GetAverage\fP (std::vector< double > a_list)"
.br
.RI "Function to get average of a list with doubles\&. "
.ti -1c
.RI "double \fBUtilities::GetStandardDeviation\fP (std::vector< double > a_list, double a_average)"
.br
.RI "Function to get the standard deviation of a list with doubles\&. "
.ti -1c
.RI "void \fBUtilities::trimBlanks\fP (std::string &a_str)"
.br
.RI "Method to trim leading and trailing blanks while reading data\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DOROTHY from the source code\&.
